project:
  type: website
  output-dir: ../docs

website:
  title: "Statistics for Engineers in a Hurry (an Illustrated Primer)"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: 1-intro.qmd
      - text: "Probability of Data"
        href: 2-data_generation.qmd
        contents:
          - 2.1-discrete_probability_distributions.qmd
          - 2.2-continuous-probability-distributions.qmd
          - 2.3-statistical_models.qmd
          - 2.4-machine_learning.qmd
      - text: "Likelihood of Model"
        href: 3-parameter_estimation.qmd
        contents:
          - 3.1-without_priors.qmd
          - 3.2-with_priors.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



