project:
  type: website
  output-dir: ../docs

website:
  title: "Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: 1-intro.qmd
      - text: "Data Generation"
        href: 2-data_generation.qmd
        contents:
          - 2.1-simple_data_generation.qmd
          - 2.2-probability_distributions.qmd
          - 2.3-tests_processes_parameters.qmd
      - text: "Parameter Estimation"
        href: 3-parameter_estimation.qmd
        contents:
          - 3.1-data_generation_reverse.qmd
          - 3.2-probability_distributions_reverse.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



