---
title: "About"
---

A note to readers and contributors alike:

I think the primer is best viewed as a set of themes within a narrative thread. First, the themes:

- That statistics is simply a loop of P(D|M) and P(M|D), where D is Data and M is Model.
- That computation/simulation is ultimately more intuitive *and* useful than excessive analytical solutions.
- Closely related to the last bullet, that generating data from models makes it easy to:
    - Understand what the model really does/knows, not what you think it does/knows.
    - Approximate solutions that are very difficult to understand or solve analytically.

Next the narrative thread:

- That the world is full of data generating processes each creating unique probability distributions.
- For any data generating process, if we can generate data from a model that approximates it, we can approximate P(D|M).
- That statisticians have named some particularly useful probability distributuions, in large part because they have [mostly] analytic solutions to P(D|M).
- Statistical models, like linear regression, can’t be understood until you see the centrality of the error term, how it assumes a probability distribution, and how it shapes the fit of the rest of the model.
- Standard statistical models have extremely limiting assumptions, like constant variance in linear regression, and modifying the model to be more realistic quickly becomes analytically intractable.
- That Machine Learning is not always statistical because it uses loss functions that may not be probabilistic, however some machine learning methods are still naturally probabilistic, like bayesian neural nets.
- With all the discussion of P(D|M), it is now easier to understand P(M|D).
- That we either fit models with or without priors.

To contributors, one of the most challenging aspects of creating the primer is balancing intuitive wordings with 'statistical correctness'. If you see area for improvement that work with the themes and narrative thread - please contribute!!


Personal note:

Although I already had a rough outline and some content, once I had a decent first draft of the primer's introduction I asked ChatGPT to sketch out a table of contents. Even with the the introduction giving a very clear direction, ChatGPT's table of contents mirrored every other statistical book I have read, and was completely different from what I was envisioning. And that's when I began to think I may be on to something meaningful.

I hope this helps you avoid a maze of confusion that I wandered through as I tried to grasp statistics. First as a graduate engineering student, and later as a professional engineer working in a risk management program of an energy utility. An even grander vision would be that someday, maybe I'll be able to feed in my intro to ChatGPT, and it will spit out something much closer to my table of contents.

-Kevin


