---
title: "Statistics for Engineers in a Hurry (an Illustrated Primer)"
---

The premise of this Primer is that Engineers do not need to become statisticians to get a basic understanding of what statistics is and how to use it. This means utilizing key subsets of general statistical knowledge combined with lots of computation...

Please use the Github repo for the book to make corrections or contributions: https://github.com/Bearsetc/SEH



Other thoughts:

A statistician would never write this. It does not carefully craft sample spaces, mapping functions, and random variables. It pans the obsession with analytic solutions in a discipline for which reality has no analytic equations. It doesn’t even contain that much math.

But the need for this is real.

The need to create a more general understanding of what statistics really does… And it’s not complicated, it’s P(D|M) and P(M|D). The thesis is that if you can model the data generating process, including its uncertainty, and you have access to a reasonable amount of compute (an absolute tiny fraction of what’s possible today), you can do all the important things that statistics does.

However, this still needs to be statistically accurate and correctly use statistical terminology correctly. If you see errors please help!!!
